name: "Validate cfg files"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate-cfg-files:
    uses: KSP-RO/BuildTools/.github/workflows/validate-cfg-files.yml@master
